title: Blogs
description: Blogger, Consultant, Technologist and Very Opinionated.
author: Michael D. Green
github: https://github.com/michaeldeongreen
about: Blogger, Consultant, Technologist and Very Opinionated.
google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-facebook
      link: "https://www.facebook.com/profile.php?id=100014250101566"
    - icon: fa-twitter
      link: "https://twitter.com/mikedeongreen"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/michael-d-green/"
    - icon: fa-github
      link: "https://github.com/michaeldeongreen"

share:
  twitter_username: mikedeongreen
  fb_appid: 100014250101566

urls:
    - text: About Me
      url: /about/
    - text: Resumé
      url: /static/attachments/Michael-Green-Resume.docx
    - text: My Projects
      url: /projects/
    - text: XML Feed
      url: /feed.xml

url: "https://blog.michaeldeongreen.com"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
